# basic options
title: Vakantie mei en juni 2019 - Frankrijk
author: Kees
description: Blog van de kampeervakantie van mei en juni 2019

# URL to GitHub repo
baseurl: "/2019-05-frankrijk" 
url: "https://prudento-nl.github.io" 

# URL to images folder at GitHub repo
images: "https://prudento-nl.github.io/2019-05-frankrijk/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
